### ISSUE TITLE
Show error message from failed output on service info

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#132]
Right now, its not possible for the user to see the error message returned by a historical build. This would be very valuable if the output is lost on the terminal and would assist in debugging.

**Comment by adriacidre** [comment]
When you run the command `ernest info` it will show you the last konwn error for the specified build, as info can display services by name and by build id, you'll have access to all errors on the system.

```
$ ernest-cli service info poo8
Name : poo8
Status : errored
Last known error : VpcLimitExceeded: The maximum number of VPCs has been reached.
	status code: 400, request id: e21803da-f0e4-43a7-b80c-7cf00aff30b7

ELBs (empty)


Networks (empty)


Instances (empty)


NAT gateways (empty)


Security groups (empty)
```
