### ISSUE TITLE
service destroy - EIPs left behind

### ISSUE THREAD

**Issue by asantos82** [ernestio/ernest#208]
When destroying a service I have noticed that Elastic IPs are left behind without being removed.
This happens to EIPs assigned to EC2, has well has EIPs assigned no NatGW/VPC

Below you can find the output of ernest cli, Prt Scrn of Elastic IP Before/After service deletion, yml of the service, and the ernest logs.

```
[asantos@fosters ~]$ ernest service destroy demo
Do you really want to destroy this service? (Y/n)Y
Deleting nats:
 - my-dc-demo-private-nat
   Status    : completed
Nats deleted
Deleting instances:
 - my-dc-demo-public-1
   IP        : 10.0.10.11
   PUBLIC IP : 52.213.170.252
   AWS ID    : i-20a49cc8
   Status    : completed
 - my-dc-demo-private-1
   IP        : 10.0.11.11
   AWS ID    : i-9da39b75
   Status    : completed
Instances deleted
Deleting networks:
 - my-dc-demo-public
   IP     : 10.0.10.0/24
   AWS ID : subnet-e2fca786
   Status : completed
 - my-dc-demo-private
   IP     : 10.0.11.0/24
   AWS ID : subnet-e3fca787
   Status : completed
Networks deleted
Deleting firewalls:
 - my-dc-demo-public-sg
   Status    : completed
 - my-dc-demo-private-sg
   Status    : completed
Firewalls deleted
SUCCESS: your environment has been successfully deleted
```

**EIPs_Before_Service_Deletion**
![EIPs_Before_Service_Deletion](https://cloud.githubusercontent.com/assets/14309894/21056454/9a928eac-be2d-11e6-9c4c-26103144a524.jpg)

**EIPs_After_Service_Deletion**
![EIPs_After_Service_Deletion](https://cloud.githubusercontent.com/assets/14309894/21056459/9f1480d4-be2d-11e6-8b76-b1bdeaa7c9ee.jpg)

[demo.yml.txt](https://github.com/ernestio/ernest/files/642691/demo.yml.txt)
[ernest.log.txt](https://github.com/ernestio/ernest/files/642705/ernest.log.txt)

**Comment by reidjc** [comment]
This is the expected behaviour. We implemented it this way with the thought of being able to re-assign EIPs, however Ernest does not currently support re-assigning an EIP.

We will modify the behaviour to release EIPs when the associated device is removed.

**Comment by purehyperbole** [comment]
This should be fixed with the recent 1.11.0 release, elastic IP's assigned to instances and nat gateways are now freed. Please would you be able to verify this has fixed your issue?

**Comment by asantos82** [comment]
Yes @purehyperbole , I am able to verify the behaviour.
I'll perform some testing, and I'll give you some feedback

**Comment by asantos82** [comment]
HI,

I have tested this and now in v1.11.0 the EIPs are removed
