### ISSUE TITLE
R&D Ernest Importing - AWS

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#222]
Investigate the best way to be able to import an existing aws service into ernest.

This feature should work by allowing the user to selectively import only the components they wish. This should be accomplished by using AWS tags, which will also be set on services created through ernest. Ernest should be able to not only scan for new environments, but also re-scan existing ones.

**Comment by purehyperbole** [comment]
New repository: github.com/ernestio/ernest-importer

Serves as a prototype standalone cli tool that allows users to select what components they want to use, and how they are grouped together. 

This should allow an internal service to scan for these tags and build the correct internal state. I believe this  approach should work for importing new services, reloading existing service components and possibly as a mechanism to re-import services when upgrading between incompatible versions of ernest.

**Comment by adriacidre** [comment]
I'm closing this issue as R&D has been moved to its own [milestone](https://github.com/ernestio/ernest/milestone/8)
