### ISSUE TITLE
Unkown fields on import

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#243]
Even aws api is so complete, there are some required fields that can't be retrieved, so we will need to find a way to get this fields.

Missing fields are:
- [ ] [S3 ACL](https://github.com/ernestio/ernestaws/blob/develop/s3/query.go#L226)
- [x] [S3 BucketURI](https://github.com/ernestio/ernestaws/blob/develop/s3/query.go#L226)
- [ ] [Nat RoutedNetworksAWSIDs](https://github.com/ernestio/ernestaws/blob/develop/nat/query.go#L168)
- [ ] [Nat InternetGatewayID](https://github.com/ernestio/ernestaws/blob/develop/nat/query.go#L169)
- [x] [RDSInstance FinalSnapshot](https://github.com/ernestio/ernestaws/blob/develop/rdsinstance/query.go#L224)

**Comment by adriacidre** [comment]
As suggested [here](https://forums.aws.amazon.com/thread.jspa?threadID=93828) we can predict the structure of the S3 BucketURI based on this pattern:
```
http(s)://<bucket>.s3.amazonaws.com/<object>
http(s)://s3.amazonaws.com/<bucket>/<object>
```

**Comment by adriacidre** [comment]
As for `rds_instance final_snapshot` is a field used only on service deletion, on imports we could assign a default value and show a warning to the end user. In case the user doesn't like the default value he can change it before deleting the service.

**Comment by bbbarnett** [comment]
moved to done by Tom as most issues have been addressed
