### ISSUE TITLE
Modify release script for ernestio/ernest develop branch

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#284]
As we are making changes to the surrounding scripts on ernestio/ernest, these changes are going live because there is no develop branch. 

These should always be merged to develop to avoid end users using potentially untested scripts.

This requires the release script to be modified so that all changes to this repo on release are pushed to develop first and then merged to master.

**Comment by adriacidre** [comment]
In addition to changes on [ernest versioner](https://github.com/ernestio/ernest-versioner/pull/4), ernestio/ernest default branch has been paired with master and set as default.

**Comment by purehyperbole** [comment]
I think for this repo we actually want master to be the default, as it's the primary repo that users build from. Setting it to develop will mean every user is building from the develop setup scripts
