### ISSUE TITLE
CLI: Windows login issue

### ISSUE THREAD

**Issue by bbbarnett** [ernestio/ernest#288]

**Comment by reidjc** [comment]
Interactive login does not work with the Windows CLI. You can only login using the options.

**Comment by adriacidre** [comment]
<img width="752" alt="screen shot 2017-03-06 at 13 30 45" src="https://cloud.githubusercontent.com/assets/593270/23610040/46807e40-0271-11e7-8c94-2e105cbf5783.png">

Read username seems to work fine, however is not asking for the password, instead is accepting an empty string, and trying to request `post /auth`
