### ISSUE TITLE
API username and password validation

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#315]
On the api-gateway::Authenticate we will need to escape the username and password as actually the system is storing the data as is provided

**Comment by g3kk0** [comment]
# Tasks

- Limit available input characters for username & password attributes (a-zA-Z0-9@._-)
- Set minimum password length to 8 characters


# Notes

- Gorm ORM provides query escaping by default.

**Comment by g3kk0** [comment]
Awaiting PR review on CLI

**Comment by g3kk0** [comment]
Feature archived (closed source)
