### ISSUE TITLE
Error creating S3 bucket with full_control permissions: "S3 grantee permissions () is not valid. Must be one of [full_control | write | write_acp | read | read_acp]".

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#332]

**Comment by reidjc** [comment]
S3 block from yaml is:

s3_buckets:
  - name: reidjc-s3-test1
    bucket_location: eu-west-1
    grantees:
      - id: jcreid@gmail.com
        type: emailaddress
        permissions: full_control

**Comment by purehyperbole** [comment]
Fix was merged on https://github.com/ernestio/definition-mapper/pull/17
