### ISSUE TITLE
Add info logs to api-gateway

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#336]
Api-gateway must be calling `logger.log` endpoint in order to write custom logs. It basically will be keeping track of user api queries, and its results

**Comment by adriacidre** [comment]
## Implementation details

# Logging API implementation


## Git / github

You'll want to start your work from ernest/307 branch, otherwise you'll have millions of conflicts when you try to merge it.

```
git checkout ernest/307
git checkout -b your_branch_name
```

When you're done your development you just open a pull request against ernest/307 branch if is still not merged

### Models

As we agreed on the specification we will be calling nats through `logger.log` subject to be directly tracking logs.

All nats communications are encapsulated inside models folder. You'll have a nats connection instance on the variable `N`. And you can have a look at base.go model as is the one used by all others (we can reuse some of the logic in there).

Basically you may want to start by defining the model, something like [this](https://github.com/ernestio/api-gateway/blob/ernest/307/models/user.go#L27).
This model will implement a public method Log, so you can do something like:
```
l := models.Logger{
  Message: "Hello",
  Body: `{"x":"y"...}`,
  User: "me"
}
l.Log()
```
Internally this log method will call `logger.log` nats endpoint with the model marshalled.

### Helpers

You may want to call this logic from the controllers, basically because you'll have accessible the username and the responses (success or error) of every action.

As it may be much code to be called on every handler, you may want to add a helper so you can call something like:
```
helpers.Log("Hello", "my_user", `{"x":"y"...}`)
```
and internally this helper will call the previous logic.

### Controllers

Now you will only need to be calling this helper from the controllers, so you can log everything you need

**Comment by g3kk0** [comment]
Feature archived (closed source)
