### ISSUE TITLE
Fix error message for password length fail on account creation

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#463]
Currently see this:

➜  demo ernest user create user2 abc123
You're not allowed to perform this action, please log in
➜  demo ernest user create user2 test1234
User user2 successfully created
➜  demo 

The error message should relate back to the password policy violation.

**Comment by g3kk0** [comment]
Fixed and merged to develop

https://github.com/ernestio/ernest-cli/commit/6d292d12341c8eb3a08f2630aaba2540beafb952
