### ISSUE TITLE
AWS NAT info not shown in 'service info' output.

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#525]
If NAT gateways are present `service info` output looks like this:
```
NAT gateways (empty)

```
Should look like this:
```
NAT gateways:
+--------+---------------------+-----------+
|  NAME  |         ID          | IP |
+--------+---------------------+-----------+
```

**Comment by adriacidre** [comment]
Fixed on:
- https://github.com/ernestio/ernest-cli/pull/88
- https://github.com/ernestio/api-gateway/pull/67
