### ISSUE TITLE
Upgrade path requires `datacenter update` to work.

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#527]
The current upgrade process is:
```
docker-compose down
git checkout docker-compose.yml && git checkout config/nginx/ernest.local && git checkout master && git pull
./setup
```
Once ernest has started up again the users need reapply the datacenter credentials for all existing datacenters with `ernest datacenter update`.

Can we improve the upgrade process so that it is not necessary to reapply the datacenter credentials?

**Comment by adriacidre** [comment]
Upgrades must be managed with `./upgrade` script. 
Maybe we could add an automatic switch on the setup script to run one or the other  in case the environment already exists.

**Comment by reidjc** [comment]
Yes that works perfectly. Sorry did not see the upgrade script before. We can close this.
