### ISSUE TITLE
Re-apply CLI

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#544]
The following command should allow the user to do an apply based on the YAML stored for the specified ‘service_name’ and ‘build_id’. The user should not have to supply a YAML file for this apply.
 
```
$ ernest service apply --name <service_name> --build <build_id>
 ```

The output from this command should be the same as for a normal ‘ernest service apply <file_name>’.

Internally CLI should:
- Validate build ID belongs to the current user and service.
- Recover the YAML for the specified build
- Apply as usual

**Comment by g3kk0** [comment]
PR: ernestio/ernest-cli#92
Tests: ernestio/ernest#546
