### ISSUE TITLE
Make "service name" available on service.create.done and service.delete.done

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#548]
In order to avoid requesting for the service name on each final event, we should make available it as part of the `service.create.done` and `service.delete.done` events.

**Comment by adriacidre** [comment]
- [ ] https://github.com/r3labs/graph/pull/3/files

**Comment by purehyperbole** [comment]
graph PR has been merged into v2 branch as thats what all dependent services are using. Will require a full rebuild of all componets as the field will be missing when other services marshal back to json.

**Comment by adriacidre** [comment]
@purehyperbole couldn't make that work, could you have a look please?
