### ISSUE TITLE
Identify CLI version

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#579]
When the CLI communicates with Ernest it would be helpful to know its version.

This would provide the following benefits:

- Enable/Disable specific features
- Identify legacy versions
- Assist with breaking changes
- Present different feedback depending on version

**Technical Details**

Leverage the User-Agent HTTP header to include the Ernest version in all requests sent to the server.

Current
```
User-Agent: Go-http-client/1.1
```

Proposed
```
User-Agent: Ernest/x.x.x
```

**Comment by adriacidre** [comment]
LGTM, added some additional changes on https://github.com/ernestio/api-gateway/pull/75 but they're only code style stuff
