### ISSUE TITLE
Show version in ernest info

### ISSUE THREAD

**Issue by g3kk0** [ernestio/ernest#588]
It would be useful to include the version of the CLI in `ernest info`.

Current:
```
$ ernest info
Current target : https://127.0.0.1/
Current user : admin
```

Proposed
```
$ ernest info
Target: https://127.0.0.1/
User: admin
Version: x.x.x
```

**Comment by adriacidre** [comment]
You'll need additional changes on ernestio/ernest integration tests to match the new output
