### ISSUE TITLE
Define availability zone for subnets/ELB's

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#64]

**Comment by purehyperbole** [comment]
Right now, availability zones are picked automatically. This limits the user's ability to spread workloads around to avoid failure of a single AZ. 

Additionally, Loadbalancers can only be configured for one subnet per availability zone. This should be possible to provide validation for at the beginning of a build, however only if the az is specified for all relevant networks.

**Comment by adriacidre** [comment]
Looks good to me. I've added a question [here](https://github.com/ernestio/aws-definition-mapper/pull/21#pullrequestreview-5014530) could you please take a look?
