### ISSUE TITLE
New credentials are not mapped to components

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#658]
Given i have a yaml with 2 networks
When I update the credentials of the project to something incorrect
And i remove both networks from the yaml and apply
Both networks delete successfully.

In this situation, the credentials on the network should have been updated and the request to delete should have failed.

This seems to only be the case on components that are marked for deletion. The correct behaviour happens for components that create/update.

**Comment by adriacidre** [comment]
It only happens with `env update` command, if you run it with `env apply` with credentials parameters works fine
