### ISSUE TITLE
Error trying to add logger configuration

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#794]
https://r3labs.slack.com/files/U04DAFDT0/F860NDRS5/error_trying_to_add_logger_configuration_.txt

**Comment by adriacidre** [comment]
Couldn't reproduce this behaviour with a fresh environment :-( 
The error logs indicate it could be a temporary problem with nats connection.

**Comment by reidjc** [comment]
I am seeing the same problem with a clean build this morning.

**Comment by reidjc** [comment]
jr-dev.r3labs.io if you want to have a look

**Comment by reidjc** [comment]
Getting the same error on a clean build this morning.

**Comment by reidjc** [comment]
And on another clean build on a different server.
