### ISSUE TITLE
CLI : delete not displaying stream info

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#823]
When deleting an environment real time information should be displayed, however atm only a success message is shown.

**Comment by reidjc** [comment]
Testing on a clean build this morning. I am still seeing the absence of stream info:

```
$ ernest env delete aws-de test -y
Environment successfully removed
$
```

**Comment by adriacidre** [comment]
Ooops, apparently there was a different logic when you use the `-y` option and when you manually confirm the action. That was only partially fixed for the manual confirmation.

I've refactored the code so the same logic is used on both cases.

Pull request with changes https://github.com/ernestio/ernest-cli/pull/150
